#!/usr/bin/env bash

CHROME="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

. ~/scripts/.app-functions.sh

if [ "$1" = "-h" -o ! -f ~/.appchromerc ]; then
  cat <<EOF

usage: $(basename $0) [<app_name>]

       <app_name>  [optional] app name to start

       Create your ~/.chromerc

       Format:
       app_name | description;url;width,height;positionX,positionY;

       Example ~/.chromerc:
       google | Google           ;https://www.google.com;
       social | Social Networks  ;https://www.twitter.com;800,600;100,100
       social | Social Networks  ;https://www.facebook.com;

       Execute:
       $(basename $0) social
       or
       $(basename $0)

EOF
  exit
fi

if [ "$1" == "" ]; then
  echo
  echo "Select one option using up/down"
  echo "keys and enter to confirm"
  echo "or Ctrl-C to abort:"

  IFS=$'\n'
  options=($(cat ~/.appchromerc | cut -f1 -d";" | sort | uniq))
  echo

  echo "   ${options[0]}"
  unset -v 'options[0]'
  select_option "${options[@]}"
  let choice=$?+1

  APP=$(echo ${options[$choice]} | cut -f1 -d' ')
else
  APP=$1
fi

if [ $(grep -e "^$APP " ~/.appchromerc | wc -l) -eq 0 ]; then
  echo "App \"$APP\" not found in ~/.chromerc"
  exit
fi

while read APP_DATA
do
  IFS=";"
  set - $APP_DATA

  URL=$2
  SIZE=$3
  POSITION=$4

  echo "Starting Chrome => $URL ..."

  if [ "$SIZE" != "" ]; then
    nohup $CHROME --app="data:text/html,<html><body><script>window.moveTo($POSITION);window.resizeTo($SIZE);window.location='$URL';</script></body></html>" > /dev/null 2>&1 &
  else
    nohup $CHROME --app="$URL" > /dev/null 2>&1 &
  fi
done <<EOF
$(grep -e "^$APP " ~/.appchromerc)
EOF
