#!/usr/bin/env bash

. ~/scripts/.app-functions.sh

if [ "$1" = "-h" -o ! -f ~/.appchromerc ]; then
  echo
  echo "usage: $(basename $0) <app_name>"
  echo
  echo "       Create your ~/.chromerc"
  echo
  echo "       Format:"
  echo "       app_name url width,height"
  echo
  echo "       Example ~/.chromerc:"
  echo "       google https://google.com.br 500,500"
  echo
  echo "       Execute:"
  echo "       $(basename $0) google"
  exit
fi

echo
echo "Select one option using up/down"
echo "keys and enter to confirm:"

IFS=$'\n'
options=($(cat ~/.appchromerc | cut -f1 -d";" | sort | uniq))
echo

echo "   ${options[0]}"
unset -v 'options[0]'
select_option "${options[@]}"
let choice=$?+1

APP=$(echo ${options[$choice]} | cut -f1 -d' ')

if [ $(grep -e "^$APP " ~/.appchromerc | wc -l) -eq 0 ]; then
  echo "App \"$APP\" not found in ~/.chromerc"
  exit
fi

while read APP_DATA
do
  IFS=";"
  set - $APP_DATA

  URL=$2
  SIZE=$3
  #POSITION=$4

  echo "Starting $URL ..."

  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app="$URL" --window-size=$SIZE 2>&1 /dev/null
done <<EOF
$(grep -e "^$APP " ~/.appchromerc)
EOF
