#!/usr/bin/env bash
#-----------------------------
# aws-ec2 (2020) fszostak
# Wed Mar 31 17:01:34 -03 2020

. ~/scripts/.app-functions.sh

function ctrl_c() {
  echo "Aborted!!!"
  [ -f $TMP ] && rm $TMP
  exit
}

if [ $# -eq 0 -o $# -gt 3 ]; then
  echo "usage: aws-ec2 [-r] <aws-profile> [<filter>]"
  echo "       options:"
  echo "       [-r]            dont read config file defaults"
  echo "       <aws-profile>   AWS Profile"
  echo "                       Configure profile with \"aws configure --profile=name\""
  echo "       example: for profile name \"customer\" you need have ~/.ssh/customer-devops.pem file"
  echo "                try the command \"aws-ec2 costumer\""
  exit
fi

if [ "$1" = "-r" ]; then
	DEFAULT=0
	shift
else
	DEFAULT=1
fi

echo

AWS_PROFILE=$1
AWS_PEM_FILE=~/.ssh/$1-devops.pem

if [ ! -f $AWS_PEM_FILE ]; then
	AWS_PEM_FILE=~/.ssh/$1-prod.pem
	if [ ! -f $AWS_PEM_FILE ]; then
		echo "\"~/.ssh/$1-devops.pem\" not found"
		exit
	fi
fi

trap ctrl_c INT
TMP=/tmp/ec2-$$.tmp
EC2_CONFIG=~/.ssh/.ec2_config
FILTER=$2
NAME=""
USERNAME=""
GATEWAY=""
EC2_FILTER=";$AWS_PROFILE;$FILTER;"

if [ -f $EC2_CONFIG ]; then
	# check config file compatibility
	IFS=';' 
	set -- $(head -1 $EC2_CONFIG)
	if [ $# -ne 8 ]; then
		> $EC2_CONFIG
	fi
	IFS=' '
else
 	touch $EC2_CONFIG
fi

if [ "$FILTER" != "" ]; then
  
  if [ $(grep "$EC2_FILTER" $EC2_CONFIG | wc -l) -gt 0 ]; then
    COUNT=$(grep "$EC2_FILTER" $EC2_CONFIG | head -1 | cut -f3 -d";")
    IP=$(grep "$EC2_FILTER" $EC2_CONFIG | cut -f2 -d";")
    NAME=$(grep "$EC2_FILTER" $EC2_CONFIG | cut -f6 -d";")
    GATEWAY=$(grep "$EC2_FILTER" $EC2_CONFIG | cut -f8 -d";")
    YN=""
    [ "$COUNT" == "" ] && COUNT=0
    if [ $COUNT -gt 1 ]; then
      echo "You want access $NAME? (Y/n)"
      read YN
    fi
    if [ "$YN" != "n" -a "$YN" != "N" ]; then
      #echo "Checking $IP ..."
      timeout 1 bash -c "</dev/tcp/$IP/22" > /dev/null 2>&1
      if [ $? -eq 0 ]; then
        USERNAME=$(grep "$EC2_FILTER" $EC2_CONFIG | cut -f1 -d";")
      else
        IP=""
      fi
    else
      IP=""
    fi
  fi
else
  FILTER="-"
fi

if [ $DEFAULT -eq 0 -o "$IP" == "" ]; then

  echo -ne "   One moment!!! Loading available EC2 instances..."

  # get active instances on AWS
  aws ec2 describe-instances \
      --profile=$AWS_PROFILE \
      --query 'Reservations[*].Instances[*].{Name:Tags[?Key==`Name`]|[0].Value,Instance:PublicIpAddress}' \
      --output='text' | grep -v -e "^None" > $TMP


  echo -ne "\r                                                   \r"
  # filter by second parameter
  if [ "$FILTER" != "-" ]; then
    grep -i $FILTER $TMP > $TMP.1
    mv $TMP.1 $TMP
  fi
  COUNT=$(cat $TMP | wc -l | sed "s/ //g")

  if [ $COUNT -gt 1 ]; then
    # order by name and first beanstalk instances
    sort -k2 -t "	" $TMP > $TMP.2
    grep -v -e "env$" $TMP.2 > $TMP.1
    grep -e "env$" $TMP.2 > $TMP
    cat $TMP.1 >> $TMP
    rm $TMP.1 $TMP.2

    # format menu output
    clear
    msg_bold "   aws-ec2 (2020) by fszostak"
    echo
    echo
    echo "   #   ip-address       environment-name                           "
    echo -ne "   --- ---------------- -----------------------------------"

    IFS=$'\n' 
    options=( 
      $(cat $TMP \
        | awk \
        'BEGIN {
          count=1;
        }
        {
          if ($1 != "None") {
            printf "%02d) %16s %-35s\n", count, $1, $2;
            count++
          }
        }'
      )
    )
    echo

    # show menu
    select_option "${options[@]}"
    choice=$?
    let choice=$choice+1

    option="$(head -$choice $TMP | tail -1)"
  else
    option="$(cat $TMP)"
  fi
  NAME=$(echo "$option" | cut -f2 -d"	")
  IP=$(echo "$option" | cut -f1 -d"	")
fi

if [ $DEFAULT -eq 1 -a "$USERNAME" == "" ]; then
  if [ -f $EC2_CONFIG ]; then
    EC2_INFO=$(grep -e ";$FILTER;!$NAME!;" $EC2_CONFIG)
    if [ $? -eq 0 ]; then
      USERNAME=$(echo $EC2_INFO | cut -f1 -d";")
    fi
  fi
fi

# username
IFS=' ' 
if [ $DEFAULT -eq 1 -a "$USERNAME" == "" ]; then
  echo "  Select user"
  echo
  options=("ec2-user" "ubuntu")
  select_option "${options[@]}"
  choice=$?
  USERNAME=${options[$choice]}
fi

if [ $DEFAULT -eq 1 -a "$GATEWAY" == "" ]; then
  if [ -f $EC2_CONFIG ]; then
    EC2_INFO=$(grep -e ";$FILTER;!$NAME!;" $EC2_CONFIG)
    if [ $? -eq 0 ]; then
      GATEWAY=$(echo $EC2_INFO | cut -f7 -d";")
    fi
  fi
fi

# gateway
IFS=' ' 
if [ $DEFAULT -eq 1 -a "$GATEWAY" == "" ]; then
  echo "  Select access method"
  echo
  options=("direct" "$AWS_PROFILE-gateway")
  select_option "${options[@]}"
  choice=$?
  GATEWAY=${options[$choice]}
fi

# connecting
echo ""
echo -ne "Connecting to ${COLOR_WHITE}$NAME${COLOR_NC} ($USERNAME@$IP)...."
echo
if [ "$GATEWAY" = "" -o "$GATEWAY" = "direct" ]; then
	ssh -o StrictHostKeyChecking=no -i $AWS_PEM_FILE $USERNAME@$IP 2> $TMP
else
	ssh -o ProxyCommand="ssh -W %h:%p $GATEWAY" -o StrictHostKeyChecking=no -i $AWS_PEM_FILE $USERNAME@$IP 2> $TMP
fi

if [ $? -eq 0 ]; then
	# update EC2_CONFIG
	grep -v -e ";$FILTER;!$NAME!;" $EC2_CONFIG > $EC2_CONFIG-$$.tmp
	echo "$USERNAME;$IP;$COUNT;$AWS_PROFILE;$FILTER;!$NAME!;$GATEWAY" >> $EC2_CONFIG-$$.tmp
	mv $EC2_CONFIG-$$.tmp $EC2_CONFIG
fi

if [ $(grep ' has changed and you have requested strict checking' $TMP | wc -l) -gt 0 ]; then
  grep -v "$1" ~/.ssh/known_hosts > /tmp/known_hosts
  cp /tmp/known_hosts ~/.ssh/known_hosts
  rm /tmp/known_hosts
  ssh --oStrictHostKeyChecking=no -i $AWS_PEM_FILE $USERNAME@$IP #2> /dev/null
fi

rm $TMP
