#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	echo "usage: $(basename $0) <profile> <beanstalk-environment-name> <desired> [<min> <max>]"
	exit 0
fi

export AWS_PAGER=""

PROFILE=$1
NAME=$2
DESIRED=$3
if [ "$4" = "" ]; then
	MIN=$DESIRED
else
	MIN=$4
fi
if [ "$5" = "" ]; then
	MAX=$MIN
else
	MAX=$5
fi

#aws autoscaling set-desired-capacity --auto-scaling-group-name $ASG --desired-capacity $DESIRED --profile $PROFILE

ASG=$(aws autoscaling describe-tags  --profile $PROFILE --output text | grep "elasticbeanstalk:environment-name" | grep $NAME | awk '{ print $4 }')
aws autoscaling describe-tags  --profile $PROFILE --output text  | grep elasticbeanstalk:environment-name | grep $NAME
if [ "$ASG" != "" ]; then
	aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG --min-size $MIN --max-size $MAX --profile $PROFILE
	[ $? -eq 0 ] && echo "Success!!!"
else
	echo "ASG not found"
fi
