#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	echo "usage: $(basename $0) <profile> <auto-scaling-group-name> <desired> <min> <max>"
	exit 0
fi

export AWS_PAGER=""

PROFILE=$1
ASG=$2
DESIRED=$3
MIN=$4
MAX=$5
if [ "$MIN" = "" ]; then
	MIN=$DESIRED
	MAX=$DESIRED
fi

aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG --min-size $MIN --max-size $MAX --profile $PROFILE
