#!/usr/bin/env bash
#-----------------------------
# docker-cleanup (2020) fszostak
# Wed Mar 31 17:01:34 -03 2020

if [ "$1" == "-h" ]; then
  echo "usage: docker-cleanup [all]"
  echo "       options:"
  echo "       all    to clean all docker resources"
  echo "       example: docker-clean or docker-clean all"
  exit
fi

docker stop $(docker ps -aq) > /dev/null 2>&1

# Cleanup exited processes:
docker rm -v $(docker ps -a -q -f status=exited) > /dev/null 2>&1

# Cleanup dangling volumes:
docker volume rm $(docker volume ls -qf dangling=true) > /dev/null 2>&1

# Cleanup dangling images:
docker rmi $(docker images --filter "dangling=true" -q --no-trunc) > /dev/null 2>&1

if [ "$1" == 'all' ]; then 
  # Remove all stopped containers
  echo y | docker container prune  > /dev/null 2>&1
  # Remove all unused volumes
  echo y | docker volume prune  > /dev/null 2>&1
  # Remove unused images
  echo y | docker image prune  > /dev/null 2>&1
  # All of the above, in this order: containers, volumes, images
  echo y | docker system prune  > /dev/null 2>&1
  echo y | docker system prune -a  > /dev/null 2>&1
fi

echo
docker ps -a
echo
docker system df
echo
[  "$1" != "all" ] && echo 'Run "docker-cleanup all" for full clean-up'
