#!/usr/bin/env bash
#-----------------------------
# docker-kill (2020) fszostak
# Wed Mar 31 17:01:34 -03 2020

. ~/scripts/.app-functions.sh

TMP=/tmp/$(basename $0).tmp

if [ "$1" == "-h" -o $# -gt 1 ]; then
  echo "usage: docker-kill [all|<filter>]"
  echo "       options:"
  echo "       all       kill all running containers"
  echo "       <filter>  word for filter \"docker ps\" results"
  exit
fi


while true
do
  if [ $# -eq 1 -a "$1" != "all" ]; then
    docker ps | grep "$1" | cut -c1-50 > $TMP
  else
    docker ps | cut -c1-50 | grep -v "CONTAINER" > $TMP
  fi

  NUM_LINES=$(cat $TMP | wc -l)

  if [ $NUM_LINES -eq 0 ]; then
    echo "No containers running"
  fi

  if [ "$1" == "all" ]; then
    CONTAINER_ID=""
    while read LINE; do
      CONTAINER_ID="$CONTAINER_ID $(echo $LINE | cut -f1 -d' ')"
    done <<EOF
    $(grep -v "CONTAINER ID" $TMP)
EOF
    echo "Killing all containers..."
    docker kill $CONTAINER_ID 
  else
    clear
    msg_bold "  docker-kill (2020) by fszostak"
    echo
    echo "  Select one container to kill using up/down keys"
    echo "  and press key enter or return to confirm:"

    IFS=$'\n' 
    options=("--- continue ---"  "----- quit -----" $(cat $TMP))
    echo

    select_option "${options[@]}"
    let choice=$?

    if [ $choice -eq 0 ]; then
      continue
    fi
    if [ $choice -eq 1 ]; then
      echo
      break
    fi

    CONTAINER_ID=$(echo ${options[$choice]} | cut -f1 -d' ')

    echo "Killing container..."
    docker kill $CONTAINER_ID 

    press_continue
  fi

rm $TMP
done

clear
