#!/usr/bin/env bash
#-----------------------------
# docker-logs (2022) fszostak
# Fri Oct 14 10:36:14 -03 2022

. ~/scripts/.app-functions.sh

TMP=/tmp/$(basename $0).tmp

if [ "$1" == "-h" -o $# -gt 1 ]; then
  echo "usage: docker-logs [<filter>]"
  echo "       options:"
  echo "       <filter>  word for filter \"docker ps\" results"
  exit
fi


while true
do
  if [ $# -eq 1 -a "$1" != "all" ]; then
    docker ps | grep "$1" | cut -c1-50 > $TMP
  else
    docker ps | cut -c1-50 | grep -v "CONTAINER" > $TMP
  fi

  NUM_LINES=$(cat $TMP | wc -l)

  if [ $NUM_LINES -eq 0 ]; then
    echo "No containers running"
  fi

	clear
	msg_bold "  docker-logs (2022) by fszostak"
	echo
	echo "  Select one container to logs using up/down keys"
	echo "  and press key enter or return to confirm:"

	IFS=$'\n' 
	options=("--- continue ---"  "----- quit -----" $(cat $TMP))
	echo

	select_option "${options[@]}"
	let choice=$?

	if [ $choice -eq 0 ]; then
		continue
	fi
	if [ $choice -eq 1 ]; then
		echo
		break
	fi

	CONTAINER_ID=$(echo ${options[$choice]} | cut -f1 -d' ')

	echo "Logging for container..."
	docker logs $CONTAINER_ID  -f

	press_continue

rm $TMP
done

clear
