#!/usr/bin/env bash

. ~/scripts/.app-functions.sh

TMP=/tmp/$(basename $0).tmp

if [ "$1" == "-h" -o $# -gt 1 ]; then
  echo "usage: docker-exec [<filter>]"
  exit
fi

if [ $# -eq 1 ]; then
  docker ps | grep -e "$1\|CONTAINER" | cut -c1-49 > $TMP
else
  docker ps | cut -c1-49 | grep -v "CONTAINER" > $TMP
fi

NUM_LINES=$(cat $TMP | wc -l)

if [ $NUM_LINES -eq 1 ]; then
  echo "No containers running"
  exit
fi

if [ $NUM_LINES -eq 2 ]; then
  cat $TMP
  CONTAINER_ID=$(tail -1 $TMP | cut -f1 -d' ')
else
  clear
  msg_bold "  docker-exec (2020) by fszostak"
  echo
  echo "  Select one app using up/down"
  echo "  keys and enter or return to confirm:"

  IFS=$'\n' 
  options=("--- continue ---" $(cat $TMP))
  echo

  select_option "${options[@]}"
  let choice=$?

  CONTAINER_ID=$(echo ${options[$choice]} | cut -f1 -d' ')
fi

echo "Running container bash..."
docker exec -it $CONTAINER_ID bash
if [ $? -eq 126 ]; then
  echo "Running container sh..."
  docker exec -it $CONTAINER_ID sh
fi

rm $TMP
