#!/usr/bin/env bash

. ~/scripts/.app-functions.sh

TMP=/tmp/$(basename $0).tmp

if [ "$1" == "-h" -o $# -gt 1 ]; then
  echo "usage: docker-exec [<filter>]"
  exit
fi

if [ $# -eq 1 ]; then
  docker ps | grep -e "$1\|CONTAINER" | cut -c1-49 > $TMP
else
  docker ps | cut -c1-49 > $TMP
fi

NUM_LINES=$(cat $TMP | wc -l)

if [ $NUM_LINES -eq 1 ]; then
  echo "No containers running"
  exit
fi

if [ $NUM_LINES -eq 2 ]; then
  cat $TMP
  CONTAINER_ID=$(tail -1 $TMP | cut -f1 -d' ')
else
  echo
  echo "Select one option using up/down keys and enter to confirm:"

  IFS=$'\n' 
  options=($(cat $TMP))
  echo

  echo "   ${options[0]}"
  unset -v 'options[0]'
  select_option "${options[@]}"
  let choice=$?+1

  CONTAINER_ID=$(echo ${options[$choice]} | cut -f1 -d' ')
fi

echo "Running container bash..."
docker exec -it $CONTAINER_ID bash
if [ $? -eq 126 ]; then
  echo "Running container sh..."
  docker exec -it $CONTAINER_ID sh
fi

rm $TMP
