#!/usr/bin/env bash

. ~/scripts/.app-functions.sh

TMP=/tmp/$(basename $0).tmp

docker ps | grep "$1 " > $TMP

if [ $(cat $TMP | wc -l) -eq 1 ]; then
  echo "Container shell..."
  docker exec -it $(cat $TMP | cut -f1 -d' ') bash 2> /dev/null
  echo $?
  [ $? -ne 0 ] && docker exec -it $(cat $TMP | cut -f1 -d' ') sh
else
  echo
  echo "Select one option using up/down keys and enter to confirm:"

  IFS=$'\n' 
  options=($(cat $TMP | cut -c1-78))
  echo

  #options=("one" "two" "three")
  select_option "${options[@]}"
  choice=$?

  # echo "Choosen index = $choice"
  # echo "        value = ${options[$choice]}" 

  echo "Container shell..."
  docker exec -it $(echo ${options[$choice]} | cut -f1 -d' ') bash 2> /dev/null
  [ $? -ne 0 ] && docker exec -it $(echo ${options[$choice]} | cut -f1 -d' ') sh
fi

rm $TMP
