#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  echo "usage: $(basename $0) <service>"
  exit 1
fi

CONTAINER=$1

docker-compose down
docker volume prune -y
docker rmi $(docker images | grep _${CONTAINER} | cut -f1 -d' ')

docker-compose up --build --force-recreate $CONTAINER
