#!/usr/bin/env bash

. ~/scripts/.app-functions.sh

TMP=/tmp/$(basename $0)$$.tmp

#if [ "$1" == "-h" -o $# -lt 1 ]; then
#  echo "usage: k-config <namespace> [<filter>]"
#  exit
#fi

#grep "\- name: arn" ~/.kube/config | cut -f3 -d' ' > $TMP
egrep "value:|\- name: arn" ~/.kube/config | sed '$!N;s/\n//' | sed 's/        value: /:/' | sed 's/- name://' | sed 's/ //g' > $TMP

cat $TMP

msg_bold "  k-config (2022) by fszostak"
echo
echo "  Select one pod using up/down"
echo "  keys and enter or return to confirm:"

IFS=$'\n' 
options=("-------- create new --------" $(cat $TMP))
echo

select_option "${options[@]}"
let choice=$?

if [ $choice -gt 0 ]; then
	CONFIG=$(echo ${options[$choice]} | cut -f1 -d' ')
	REGION=$(echo $CONFIG | cut -f4 -d':')
	CLUSTER=$(echo $CONFIG | cut -f6 -d':' | sed 's/cluster\///')
	PROFILE=$(echo $CONFIG | cut -f7 -d':')
else
	echo -n "Region: "
	read REGION
	echo -n "Cluster: "
	read CLUSTER
	echo -n "Profile: "
	read PROFILE
fi

aws eks --region $REGION update-kubeconfig --name $CLUSTER --profile $PROFILE
rm $TMP
