#!/usr/bin/env bash

. ~/scripts/.app-functions.sh

TMP=/tmp/$(basename $0)$$.tmp

if [ "$1" == "-h" -o $# -lt 1 ]; then
  echo "usage: k-delete <namespace> [<filter>]"
  exit
fi

NAMESPACE=$1
FILTER=$2

if [ "$FILTER" != "" ]; then
  kubectl get pods -n $NAMESPACE | grep -e "$FILTER\|NAME" | cut -c1-49 > $TMP
else
  kubectl get pods -n $NAMESPACE | cut -c1-49 | grep -v "^NAME" > $TMP
fi

NUM_LINES=$(cat $TMP | wc -l)

if [ $NUM_LINES -eq 1 ]; then
  echo "No pods running"
  exit
fi

if [ $NUM_LINES -eq 2 ]; then
  cat $TMP
  POD=$(tail -1 $TMP | cut -f1 -d' ')
else
  clear
  msg_bold "  k-delete (2021) by fszostak"
  echo
  echo "  Select one pod using up/down"
  echo "  keys and enter or return to confirm:"

  IFS=$'\n' 
  options=("--- continue ---" $(cat $TMP))
  echo

  select_option "${options[@]}"
  let choice=$?

  POD=$(echo ${options[$choice]} | cut -f1 -d' ')
fi

[ "$POD" != "" ] && kubectl delete pod $POD -n $NAMESPACE 

rm $TMP
