#!/usr/bin/env bash

. ~/scripts/.app-functions.sh

TMP=/tmp/$(basename $0)$$.tmp

if [ "$1" == "-h" -o $# -lt 1 ]; then
  echo "usage: k-exec <namespace> [<filter>]"
  exit
fi

NAMESPACE=$1
FILTER=$2

if [ "$FILTER" != "" ]; then
  kubectl get pods -n $NAMESPACE | grep "$FILTER" | cut -c1-70 > $TMP
else
  kubectl get pods -n $NAMESPACE | grep -v "NAME" | cut -c1-70 > $TMP
fi

NUM_LINES=$(cat $TMP | wc -l)

if [ $NUM_LINES -eq 0 ]; then
  echo "No pods running"
  exit
fi

if [ $NUM_LINES -eq 1 ]; then
	  echo "   NAME                                READY   STATUS    RESTARTS   AGE"
  cat $TMP
  POD=$(tail -1 $TMP | cut -f1 -d' ')
else
  clear
  msg_bold "  k-exec (2021) by fszostak"
  echo
  echo "  Select one pod using up/down"
  echo "  keys and enter or return to confirm:"
	echo
	echo "   NAME                                READY   STATUS    RESTARTS   AGE"

  IFS=$'\n' 
  options=("---  exit  -----" $(cat $TMP))
  echo

  select_option "${options[@]}"
  let choice=$?

	[ $choice -eq 0 ] && exit

  POD=$(echo ${options[$choice]} | cut -f1 -d' ')
fi

echo "Running pod bash..."
kubectl exec -it $POD -n $NAMESPACE -- bash
if [ $? -eq 126 ]; then
  echo "Running container sh..."
  kubectl exec -it $POD -n $NAMESPACE -- sh
fi

rm $TMP
