#!/usr/bin/env bash

. ~/scripts/.app-functions.sh

TMP=/tmp/$(basename $0)$$.tmp

if [ "$1" == "-h" -o $# -lt 1 ]; then
  echo "usage: k-logs <namespace> [<filter>]"
  exit
fi

NAMESPACE=$1
FILTER=$2

if [ "$FILTER" != "" ]; then
  kubectl get pods -n $NAMESPACE | grep -e "$FILTER\|NAME" | cut -c1-70 > $TMP
else
  kubectl get pods -n $NAMESPACE | cut -c1-70 | grep -v "^NAME" > $TMP
fi

NUM_LINES=$(cat $TMP | wc -l)

if [ $NUM_LINES -eq 1 ]; then
  echo "No pods running"
  exit
fi

if [ $NUM_LINES -eq 2 ]; then
  cat $TMP
  POD=$(tail -1 $TMP | cut -f1 -d' ')
else
	LOOP=0
	while true
	do
		clear
		if [ $LOOP -eq 0 ]; then
			msg_bold "  k-logs (2021) by fszostak"
			echo
			echo "  Select one pod using up/down"
			echo "  keys and enter or return to confirm:"

			IFS=$'\n' 
			options=("-------- refresh --------" "---- sleep + refresh ----" $(cat $TMP))
			echo

			select_option "${options[@]}"
			let choice=$?
		else
			msg_bold "k-logs (2021) by fszostak"
			echo
			echo
			cat $TMP
			echo
			echo "ENTER to reload or CTRL-C to exit"
		fi

		if [ $choice -gt 1 ]; then
			POD=$(echo ${options[$choice]} | cut -f1 -d' ')
			break
		elif [ $choice -eq 1 ]; then
			LOOP=1
			read -t 5
		else
			if [ "$FILTER" != "" ]; then
				kubectl get pods -n $NAMESPACE | grep -e "$FILTER\|NAME" | cut -c1-70 > $TMP
			else
				kubectl get pods -n $NAMESPACE | cut -c1-70 | grep -v "^NAME" > $TMP
			fi
		fi
	done
fi

kubectl logs $POD -n $NAMESPACE -f

rm $TMP
