#!/usr/bin/env bash
#-----------------------------
# k-mem (2022) fszostak
# Thu 24 Feb 2022 08:11:29 AM -03
#
# Show memory usage of namespace

if [ $# -eq 0 ]; then
  echo "usage: k-mem <namespace>"
  exit
fi

NAMESPACE=$1

echo "$(date +'%F %T')"
echo "Usage of pods from $NAMESPACE"
SUM=0; for N in $(kubectl top pods -n $NAMESPACE| awk '{print $2 }' | sed 's/m//' | grep -v CPU); do let SUM=$SUM+$N; done; echo "cpu ${SUM}m"
SUM=0; for N in $(kubectl top pods -n $NAMESPACE| awk '{print $3 }' | sed 's/Mi//' | grep -v MEMORY); do let SUM=$SUM+$N; done; echo -n "memory ${SUM}Mi"
echo
