#!/usr/bin/env bash

# Fabio Szostak
# Thu 11 Mar 2021 06:37:34 AM -03

for NAMESPACE in  $(kubectl get namespaces | egrep 'develop|staging|production' | awk '{print $1}')
do
	echo
	echo "NAMESPACE: $NAMESPACE"

	kubectl get pods -n $NAMESPACE
	while [ $(kubectl get pods -n $NAMESPACE | grep "0/1" | wc -l) -gt 0 ]
	do
		echo "Waiting all pods running on $NAMESPACE ..."
		sleep 3
		kubectl get pods -n unimed-portal-$branch
	done
	echo
done

