#!/usr/bin/env bash

if [ $# -lt 2 -o $# -gt 3 ]; then
  echo "usage: $(basename $0) [-a] service-name username"
  echo "       -a             to add new secret password"
  echo "       service-name   service name. ex dockerhub"
  echo "       user-name      user name. ex myaccount"
  exit
fi

[ ! -d ~/.secret ] && mkdir ~/.secret

if [ ! -f ~/.secret/.seed.secret ]; then
  echo -e "Seed: "
  read SEED
  echo "$SEED" > ~/.secret/.seed.secret
else
  SEED="$(cat ~/.secret/.seed.secret)"
fi

if [ "$1" = "-a" ]; then
  SERVICE=$2
  USER=$3

  if [ -f ~/.secret/$SERVICE-$USER.secret ]; then
    echo "Password already exists"
    exit
  fi

  echo -e "Password: "
  read SECRET
  echo "$SECRET" | openssl aes-256-cbc -pass pass:$SEED -a -in /dev/stdin -out ~/.secret/$SERVICE-$USER.secret
else
  SERVICE=$1
  USER=$2

  if [ ! -f ~/.secret/$SERVICE-$USER.secret ]; then
    echo "Password not exists"
    exit
  fi

  openssl aes-256-cbc -pass pass:$SEED -d -a -in ~/.secret/$SERVICE-$USER.secret -out /dev/stdout 
fi


